### ISSUE TITLE
Question about QuestionAnswer and SemanticSearch

### ISSUE THREAD

**Issue by samuelgjekic** [theodo-group/LLPhant#105]
Hey! Love the library, after testing it out i can really say it will save me a lot of time. 

Anyways, i am not sure im posting this in the correct place, i am sorry, if so, feel free to remove the issue.

I am trying out the QuestionAnswer class, i did try to scim it a bit to understand it better, the only thing that i am uncertain of, is the actuall fetching of the files, does the AI always fetch file and look for something? 

I mean, lets say i start a conversation saying "hello!", all i need from the AI is a simply reply "hey there!", but if i am using QuestionAnswer, does the AI always load the files? The files in the future will be large and have a lot of text, i would want to avoid checking the file untill its neccesary. 

If the answer is yes, QuestionAnswer always reads file, should i give the Ai a function instead to use the QuestionAnswer when it needs to find something in file? Because its not always going to have to look into the file. 

Also, i switched from the openai client php assistans api to this library, in my code, i save the assistant thread id in the session, so if the user goes to another page the conversation is still saved as it is still in the thread.  To achieve this with this library, im guessing i have to save the conversation to a database to continue the conversation? 

Whats the best way for approaching this? Thanks!

**Comment by MaximeThoonsen** [comment]
Hey @samuelgjekic, thanks for the kind words!

The first big step is : 

1. Read the text from your file
2. create smaller chunks of texts
3. send these chunks of text to an embedding model (like openai embedding model)
4. store each vectors in a vectorstore like postgresql or Qdrant 

![embeddings-flow](https://github.com/theodo-group/LLPhant/assets/4814551/2178b7a1-d872-4300-a37d-248b85bf42bf)

Then for each question LLPhant will :

1. take the question from the user,
2. create a vector using the same model (it's important otherwise it makes no sense)
3. search the 4 closest vectors in the vectorstore
4. use the texte from theses vectore to generate the answer

So you will need to vectorize only once all your file and it is not usually very expensive.
I hope it answers your question?

For the thread assistant, yes I haven't coded anything in LLPhant to use it directly yet. So you need to keep the thread id somewhere like in the session or a database as you have correctly guess.

**Comment by samuelgjekic** [comment]
Thank you @MaximeThoonsen for the quick reply! 

I got a clear picture of how it works now, appriciated! 

Have a nice week 🙂

**Comment by MaximeThoonsen** [comment]
If you have any suggestion on how to improve the doc, they are very welcome!
