### ISSUE TITLE
add MySQL as Vector Store

### ISSUE THREAD

**Issue by sachingk** [theodo-group/LLPhant#15]
Most of the PHP projects are on MySQL. Using yet another database for vector store is extra maintenance. Please add MySQL support for VectorStore

**Comment by MaximeThoonsen** [comment]
Hey @sachingk,
Yes I agree it is a problem. For now only PG has a system to store and search embeddings.
Maybe it will change soon: https://blogs.oracle.com/cloud-infrastructure/post/vector-store-generative-ai-mysql-heatwave

If you don't have a crazy amount of data, filesystem can work.
Are you using Redis ou elasticsearch already?

**Comment by sachingk** [comment]
I make use of Redis to cache the permission of the active users. I mostly use the Redis as a temporary storage. File systems don't work well when developing a SaaS-based application.

**Comment by MaximeThoonsen** [comment]
Ok great. We will work on Redis integration then and we will let you know. cc @Th0masso

**Comment by simpleenigma** [comment]
I am looking at creating a SAAS e-commerce application that will also need a good vector store. I am also running on AWS, but I had considered doing Postgres serverless as a solution. Redis would be much better for me in the long run. I am still creating a technical prototype, so I plan on using the file system for a while.

**Comment by MaximeThoonsen** [comment]
Qdrant is also a really good option for a SAAS e-commerce: https://cloud.qdrant.io

**Comment by sachingk** [comment]
> I am looking at creating a SAAS e-commerce application that will also need a good vector store. I am also running on AWS, but I had considered doing Postgres serverless as a solution. Redis would be much better for me in the long run. I am still creating a technical prototype, so I plan on using the file system for a while.

Why do you need a vector store for building a SAAS e-commerce application? Just curious...

**Comment by simpleenigma** [comment]
I already have a SAAS E-Commerce platform. I want to create a smart PIM and a chatbot for the site with product knowledge from the system. So, I'm extending what I already have.

**Comment by MaximeThoonsen** [comment]
One example of GenAI E-commerce: https://www.knxt-madeline.com/

**Comment by simpleenigma** [comment]
I saw that in the docs, which is the direction of the solution I am heading. 

My platform works with distribution companies that run a specific ERP. So, the source data has the same structure for about thirty companies. I plan on creating chatbots with specific product information for each company and then updating my PIM to use the data so that they can update their product data faster, easier, and more accurately. Adding a few other data sources for additional text should create a feedback loop that the chatbot gets better when the customer updates their products based on the chatbot's suggestions.

Then, I'll be looking to add SEO info with feeds from places like Serpapi, which should be able to add SEO context and hopefully improve organic search.

With any luck, the system should be good enough to take the task of updating product descriptions out of the hands of experts, like top sales reps, and into the hands of staff with more time.

**Comment by MaximeThoonsen** [comment]
i'm closing this as it seems ok
