### ISSUE TITLE
Advice needed - Ability to iterate over several tools/functions, best practices?

### ISSUE THREAD

**Issue by BoweFrankema** [theodo-group/LLPhant#16]
Hi Maxime, 

This is an awesome initiative, I'd love to get started and hopefully contribute wherever possible! I went over your docs and examples and coming from Langchain and Llamaindex I think I have a reasonable understanding on how to use the framework, but I would like your advice on how to handle something like this. 

### Setup:
"Prompt: Your task is to help the user with day to day maintenance tasks for their web agency. You can use several functions to retrieve information. Here are the tools you can use to get info 
*tool/function list + description*
When you have enough information to answer the question provide a response with the following tone.
*custom prompt instructions*

### Example 
- User asks: Which of my client sites need to be updated? And what needs to be done?
- Agent Tool: Get Sites
   use function (GetSitesOfClientWithUpdates($client)
   Result: $sitesarray
- Agent Tool: Get Tasks
   user function (GetSiteTasks($sites array)
   Result: *json response of all tasks for all sites*
- Agent Tool: Analyse JSON and answer
Final Answer: Your site hallo.com has dropped in performance, we should probably look at improving it! goodbye.com has an SSL certificate that expires next week. 

Do you think that LLPhant could achieve something like this already? I'm using Laravel and I could "loop" over responses and iterate, but if I understand correctly you might have already planned for this exact usage and you could provide me with an example of guidance?

Have a good day, and thanks for starting this project

**Comment by MaximeThoonsen** [comment]
Hey @BoweFrankema,
Yes I think you can build something like this. It would look like AutoPHP but more specialized. It could even work with AutoPHP with the right functions.

Few advices:
- Max 3 functions to the agent otherwise performance drops (2 is fine)
-  "json response of all tasks for all sites" should not be super long 
- you need to explain how you will prioritize the tasks to be done 
- Start with one client site and make your agent return "action needed: XXX" or "no action needed". After that you can just loop over you client sites.

I hope it helps. Please feel free to ask other questions

**Comment by BoweFrankema** [comment]
Thank you Maxime! That's really helpful! I'm going to play around this in the upcoming weeks. I already have a base prototype working so it's now just a matter of learning the framework and seeing how far I'll get. I'll absolutely report back once I'm a bit further ahead!
